//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KensuiteAPI.BrassRingJobs {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://integrationuri.org/", ConfigurationName="BrassRingJobs.WebRouterSoap")]
    public interface WebRouterSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://integrationuri.org/route", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string route(string inputXml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://integrationuri.org/route", ReplyAction="*")]
        System.Threading.Tasks.Task<string> routeAsync(string inputXml);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebRouterSoapChannel : KensuiteAPI.BrassRingJobs.WebRouterSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebRouterSoapClient : System.ServiceModel.ClientBase<KensuiteAPI.BrassRingJobs.WebRouterSoap>, KensuiteAPI.BrassRingJobs.WebRouterSoap {
        
        public WebRouterSoapClient() {
        }
        
        public WebRouterSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebRouterSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebRouterSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebRouterSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string route(string inputXml) {
            return base.Channel.route(inputXml);
        }
        
        public System.Threading.Tasks.Task<string> routeAsync(string inputXml) {
            return base.Channel.routeAsync(inputXml);
        }
    }
}
